### ISSUE TITLE
Proxy issues with v5.0

### ISSUE THREAD

**Issue by kraftto** [halestudio/hale#1017]
Applying proxy settings apparently doesn't work - neither as a system property in HALE.ini nor via settings window.

Log entry regarding system property:
```
eclipse.buildId=unknown
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean

org.eclipse.core.net
Info
Wed Jan 11 16:57:36 CET 2023
System property http.proxyPort has been set to 3128 by an external source. This value will be overwritten using the values from the preferences
```
Regarding proxy setting in HALE:
```
eclipse.buildId=unknown
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean

eu.esdihumboldt.util.http
Error
Wed Jan 11 16:58:55 CET 2023
Error executing proxy initializer

java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lorg.eclipse.core.net.proxy.IProxyData; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lorg.eclipse.core.net.proxy.IProxyData; is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @42971156)
	at eu.esdihumboldt.hale.ui.util.proxy.ProxySettings.applyProxyData(ProxySettings.java:152)
	at eu.esdihumboldt.hale.ui.util.proxy.ProxySettings.applyCurrentSettings(ProxySettings.java:142)
	at eu.esdihumboldt.hale.ui.util.proxy.ProxySettings$1.run(ProxySettings.java:66)
	at eu.esdihumboldt.util.http.ProxyUtil.init(ProxyUtil.java:121)
	at eu.esdihumboldt.util.http.ProxyUtil.findProxy(ProxyUtil.java:49)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
	at eu.esdihumboldt.hale.io.haleconnect.internal.ApiClientHelper.setApiClientProperties(ApiClientHelper.groovy:103)
	at eu.esdihumboldt.hale.io.haleconnect.internal.UserServiceHelper.getApiClient(UserServiceHelper.groovy:63)
	at eu.esdihumboldt.hale.io.haleconnect.internal.UserServiceHelper.getLoginApi(UserServiceHelper.groovy:75)
	at eu.esdihumboldt.hale.io.haleconnect.internal.HaleConnectServiceImpl.login(HaleConnectServiceImpl.groovy:346)
	at eu.esdihumboldt.hale.io.haleconnect.ui.HaleConnectLoginHandler$1.run(HaleConnectLoginHandler.java:92)
	at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor$1.run(ThreadProgressMonitor.java:122)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by florianesser** [comment]
Hi @kraftto, thanks for reporting this problem!

**Comment by kraftto** [comment]
Thanks for the quick fix, can you estimate when you release it? Right now we can't really use HALE :)

**Comment by florianesser** [comment]
@kraftto We've planned to do a bugfix release in January that will contain this fix. In the meantime, you can use the [latest development build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/) that already contains the fix.

**Comment by thorsten-reitz** [comment]
Fixed with release.
