### ISSUE TITLE
Regex Analysis and Formatted String mapping on source property with value and attribute not working

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#1025]
For regex analysis function, the stacktrace is the following with a ConverterNotFoundException:

Stacktrace:
`ERROR e.e.h.c.a.t.r.i.DefaultTransformationReporter(169) - Skipping property transformation: Executing property transformation failed. (2 times)
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type eu.esdihumboldt.hale.common.instance.model.impl.DefaultInstance to type java.lang.String
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:475) ~[spring-core-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175) ~[spring-core-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:154) ~[spring-core-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at eu.esdihumboldt.hale.common.align.transformation.function.impl.PropertyValueImpl.getValueAs(PropertyValueImpl.java:77) ~[eu.esdihumboldt.hale.common.align-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.functions.string.RegexAnalysis.evaluate(RegexAnalysis.java:65) ~[eu.esdihumboldt.cst.functions.string-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.align.transformation.function.impl.AbstractSingleTargetPropertyTransformation.evaluate(AbstractSingleTargetPropertyTransformation.java:57) ~[eu.esdihumboldt.hale.common.align-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.align.transformation.function.impl.AbstractPropertyTransformation.execute(AbstractPropertyTransformation.java:102) ~[eu.esdihumboldt.hale.common.align-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.internal.FunctionExecutor.executeTransformation(FunctionExecutor.java:224) ~[eu.esdihumboldt.cst-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.internal.FunctionExecutor.processValid(FunctionExecutor.java:133) ~[eu.esdihumboldt.cst-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.visitor.CellNodeValidator.visit(CellNodeValidator.java:110) ~[eu.esdihumboldt.hale.common.align-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.CellNodeImpl.accept(CellNodeImpl.java:103) ~[eu.esdihumboldt.hale.common.align-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TargetNodeImpl.accept(TargetNodeImpl.java:177) ~[eu.esdihumboldt.hale.common.align-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TransformationTreeImpl.accept(TransformationTreeImpl.java:129) ~[eu.esdihumboldt.hale.common.align-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer$2.lambda$0(TreePropertyTransformer.java:224) ~[eu.esdihumboldt.cst-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.core.report.SimpleLogContext.withLog(SimpleLogContext.java:112) ~[eu.esdihumboldt.hale.common.core-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer$2.run(TreePropertyTransformer.java:181) ~[eu.esdihumboldt.cst-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer.publish(TreePropertyTransformer.java:264) ~[eu.esdihumboldt.cst-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.functions.core.Retype.execute(Retype.java:76) ~[eu.esdihumboldt.cst.functions.core-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.ConceptualSchemaTransformer.doTypeTransformation(ConceptualSchemaTransformer.java:327) ~[eu.esdihumboldt.cst-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.cst.ConceptualSchemaTransformer.transform(ConceptualSchemaTransformer.java:155) ~[eu.esdihumboldt.cst-4.2.0-SNAPSHOT.jar:na]
	at eu.esdihumboldt.hale.common.headless.transform.Transformation$5.run(Transformation.java:398) [eu.esdihumboldt.hale.common.headless-4.2.0-SNAPSHOT.jar:na]
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63) [org.eclipse.core.jobs-3.10.700.v20200106-1020.jar:na]`

First investigation dev team: "it appears to happen only for Regex Analysis cells that map from a source property that has both a value itself as well as an attribute (like gml:identifier or gml:description). If I change the source property e.g. to id, it works. When the source property is set to identifier, the transformation fails and a Java Object description shows up in the field "Sample text"."

Update: This is not happening only for Regex Analysis but at least as well for Formatted String mapping. There is no error message in that case but the target property contains values such as `eu.esdihumboldt.hale.common.instance.orient.storage.DatabaseHandle$InstanceHandle@1008ac5f`

**Comment by JohannaOtt** [comment]
@emanuelaepure10 Can this issue be closed with [this PR](https://github.com/halestudio/hale/pull/1123) being merged in the meantime?

**Comment by JohannaOtt** [comment]
@emanuelaepure10 Can this issue be closed?

**Comment by emanuelaepure10** [comment]
It will go in the next release. So, be free to follow the usual workflow.

**Comment by JohannaOtt** [comment]
@florianesser What is the usual workflow? Are issues closed as soon as a fix is available or only once it is released?

**Comment by florianesser** [comment]
Was fixed in [this commit](https://github.com/halestudio/hale/commit/2493822d4623911dd3b0d45b49d565b9f50efb7f).

**Comment by emanuelaepure10** [comment]
The issue has been solved with the release of version [5.2.0](https://github.com/halestudio/hale/releases/tag/v5.2.0).

**Comment by emanuelaepure10** [comment]
The issue has been solved with the release of version [5.2.0](https://github.com/halestudio/hale/releases/tag/v5.2.0).
