### ISSUE TITLE
Error in display of transformed data

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#128]
When switching between synchronisation models in the Transformed Data view, I often get the following error:
```
Problems occurred when invoking code from plug-in: "org.eclipse.jface".

java.lang.IllegalStateException: Need an underlying widget to be able to set the input.(Has the widget been disposed?)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1692)
	at eu.esdihumboldt.hale.ui.views.data.internal.filter.SampleTransformInstanceSelector$InstanceSelectorControl.updateFeatureTypesSelection(SampleTransformInstanceSelector.java:285)
	at eu.esdihumboldt.hale.ui.views.data.internal.filter.SampleTransformInstanceSelector$InstanceSelectorControl.updateInDisplayThread(SampleTransformInstanceSelector.java:174)
	at eu.esdihumboldt.hale.ui.views.data.internal.filter.SampleTransformInstanceSelector$InstanceSelectorControl.access$0(SampleTransformInstanceSelector.java:172)
	at eu.esdihumboldt.hale.ui.views.data.internal.filter.SampleTransformInstanceSelector$InstanceSelectorControl$2.update(SampleTransformInstanceSelector.java:126)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at eu.esdihumboldt.hale.ui.service.instance.sample.internal.InstanceSampleServiceImpl.setReferenceInstances(InstanceSampleServiceImpl.java:52)
	at eu.esdihumboldt.hale.ui.views.data.SourceDataView.onSelectionChange(SourceDataView.java:97)
	at eu.esdihumboldt.hale.ui.views.data.AbstractDataView.selectionChanged(AbstractDataView.java:346)
	at eu.esdihumboldt.hale.ui.views.data.internal.filter.InstanceServiceSelector$InstanceSelectorControl.updateSelection(InstanceServiceSelector.java:427)
	at eu.esdihumboldt.hale.ui.views.data.internal.filter.InstanceServiceSelector$InstanceSelectorControl$2.selectionChanged(InstanceServiceSelector.java:159)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:160)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2197)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1228)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1257)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:236)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:408)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
```
Also, an additional dropdown appears that is empty an inactive.

Steps for reproduction:
1. Load ALKIS to INSPIRE Addresses Project
2. Pick `AX_LageBezeichnungMitHausnummer` as the Source Data Type
3. Pick Random/Filtered Instances
4. Pick  `Address`

**Comment by thorsten-reitz** [comment]
![hale-screenshot-error](https://cloud.githubusercontent.com/assets/3470356/17558865/5ed7903a-5f1c-11e6-9482-bfa83fb23146.png)
