### ISSUE TITLE
Target URL should be trimmed in AppSchema REST export

### ISSUE THREAD

**Issue by ilkkarinne** [halestudio/hale#176]
Hi,

I'm facing a problem with exporting HALE alignments as Geoserver App-Schema REST [Direct Upload]: The export always fails with HTTP exception "Method Not Allowed".

The Geoserver I'm using is a local installation straight from the OS X installer with no additional workspaces or other customisation. I have tried both Geoserver 2.8.5 and 2.9.1 running on the packaged jetty, the result is the same.

Based on the Geoserver log it seems to me that HALE is trying to make a DELETE operation for following resource: /rest/workspaces/nns/datastores/target.xml The "nns" workspace does not exist on the Geoserver.

The alignment is a very simple one based of the ProtectedSites project created by the INSPIRE Interactive Data Specifications application (http://inspire-regadmin.jrc.ec.europa.eu/dataspecification/FindYourScope.action). The source schema is the PS 4.0 XML Schema (http://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd) and the source data is read from a local GML file containing a wfs:FeatureCollection of ProtectedSite 4.0 features (identity transformation).

I'm using the HALE 3.0.0 from the installed with the Mac Installer from https://www.wetransform.to/downloads/

Stack trace:

`eu.esdihumboldt.hale.io.geoserver.rest.ResourceException: org.apache.http.client.HttpResponseException: Method Not Allowed
    at eu.esdihumboldt.hale.io.geoserver.rest.AbstractResourceManager.delete(AbstractResourceManager.java:302)
    at eu.esdihumboldt.hale.io.appschema.writer.AppSchemaMappingUploader.publishAppSchemaDataStore(AppSchemaMappingUploader.java:121)
    at eu.esdihumboldt.hale.io.appschema.writer.AppSchemaMappingUploader.handleMapping(AppSchemaMappingUploader.java:80)
    at eu.esdihumboldt.hale.io.appschema.writer.AbstractAppSchemaConfigurator.execute(AbstractAppSchemaConfigurator.java:92)
    at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:102)
    at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:687)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.apache.http.client.HttpResponseException: Method Not Allowed
    at eu.esdihumboldt.hale.io.geoserver.rest.AbstractResourceManager$EmptyResponseHandler.handleResponse(AbstractResourceManager.java:463)
    at eu.esdihumboldt.hale.io.geoserver.rest.AbstractResourceManager$EmptyResponseHandler.handleResponse(AbstractResourceManager.java:1)
    at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
    at eu.esdihumboldt.hale.io.geoserver.rest.AbstractResourceManager.delete(AbstractResourceManager.java:299)
    ... 6 more
`

**Comment by ilkkarinne** [comment]
Ok, I think I know the cause for this now: I typed the Target URL of the Geoserver with the trailing slash "http://localhost:8080/geoserver/", which was causing the issue. Without the trailing slash the exception is not thrown.

<img width="559" alt="screen shot 2016-09-29 at 16 50 48" src="https://cloud.githubusercontent.com/assets/2580289/18956676/f094c85c-8664-11e6-95c4-6f4374e3c7eb.png">

**Comment by ilkkarinne** [comment]
The Target URL should be canonicalised by trimming the possible trailing forward slash. It's also recommended to investigate the reason behind the original 405 symptom caused by the extra trailing forward slash in the Target URL.
