### ISSUE TITLE
Fix Export -> Project Archive

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#193]
While it is possible to create a Project Archive through `File -> Save Alignment Project as...`, the function `Export -> Project Archive` currently fails silently.

**Comment by thorsten-reitz** [comment]
eclipse.buildId=unknown
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean -clean -data C:\Users\Thorsten\AppData\Roaming\wetransform\HALE

eu.esdihumboldt.hale.ui
Error
Fri Oct 07 14:51:06 CEST 2016
Could not launch I/O wizard for advisor eu.esdihumboldt.hale.io.archive.export

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at eu.esdihumboldt.hale.ui.io.IOWizard.getPreviousPage(IOWizard.java:344)
	at org.eclipse.jface.wizard.WizardPage.getPreviousPage(WizardPage.java:179)
	at org.eclipse.jface.wizard.WizardDialog.updateButtons(WizardDialog.java:1317)
	at org.eclipse.jface.wizard.WizardDialog.update(WizardDialog.java:1305)
	at org.eclipse.jface.wizard.WizardDialog.showStartingPage(WizardDialog.java:1258)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:599)
	at org.eclipse.jface.window.Window.create(Window.java:430)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1096)
	at org.eclipse.jface.window.Window.open(Window.java:792)
	at eu.esdihumboldt.hale.ui.io.action.IOWizardAction.run(IOWizardAction.java:121)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:117)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:1)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.run(AbstractApplication.java:51)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.start(AbstractApplication.java:33)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by florianesser** [comment]
Fixed in PR #237
