### ISSUE TITLE
Joins on File Geodatabase Tables lead to errors and unexpected behaviour

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#210]
Joining multiple tables of a File Geodatabase can lead to unexpected behaviour for all fields that have the same local name in the joined types. Typical errors include:

- Multiple Values for Source node without transformation context match
- Error performing Property transformations (with an NPE stacktrace; see below)

Viewing the properties of an entity in a FGDB schema shows that it does not have a namespace, so maybe one needs to be included.

Stacktrace:

```
java.lang.NullPointerException
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.visitor.InstanceVisitor.visit(InstanceVisitor.java:142)
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.SourceNodeImpl.accept(SourceNodeImpl.java:167)
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TransformationTreeImpl.accept(TransformationTreeImpl.java:136)
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer$2.run(TreePropertyTransformer.java:198)
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer.publish(TreePropertyTransformer.java:250)
	at eu.esdihumboldt.cst.functions.groovy.GroovyRetype.execute(GroovyRetype.java:64)
	at eu.esdihumboldt.cst.ConceptualSchemaTransformer.doTypeTransformation(ConceptualSchemaTransformer.java:324)
	at eu.esdihumboldt.cst.ConceptualSchemaTransformer.transform(ConceptualSchemaTransformer.java:154)
	at eu.esdihumboldt.hale.ui.service.instance.internal.orient.OrientInstanceService$5.run(OrientInstanceService.java:464)
	at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor$1.run(ThreadProgressMonitor.java:121)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by thorsten-reitz** [comment]
Addendum: The stated exception happens also for joins on other types of data sources. There is no specific FGDB issue at hand.
