### ISSUE TITLE
Saving to Spatialite makes hale studio unresponsive; no spaces allowed in save path

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#466]
I loaded the example project Basic Hydrography and tried to save the transformed data using the sqlite/spatialite export, which makes hale completely unresponsive. The resultant sqlite file is 0K in size.

As a sidenote, it is also not possible to save sqlite files with a space in the file path.

**Comment by stempler** [comment]
Would be helpful if you can attach the SpatiaLite db you used as target schema.

**Comment by thorsten-reitz** [comment]
I used a new / empty DB as target (i.e. a new filename).

**Comment by stempler** [comment]
> I used a new / empty DB as target (i.e. a new filename).

I assume here you mean the target data file you export to?

From the [documentation on the SpatiaLite export](http://help.halestudio.org/latest/topic/eu.esdihumboldt.hale.doc.user/html/reference/export/sqlite.html?cp=0_6_2_1_7):

> Support for SQLite and SpatiaLite in hale studio is based on the generic Database export based on JDBC, and thus has the same limitations. For instance hale studio needs the database schema to already exist, thus you can only write to files that have already been prepared and loaded as target schema.
>
> The database export in this version of hale studio is deemed experimental. This means it does not have the full functionality we want to provide for a database export feature. However, within its limits it is functional and may be useful to you.
>
> ...

**Comment by thorsten-reitz** [comment]
I expected that limit to exist, but I would neither expect hale to become completely unresponsive, nor should it be a problem when a space exists in the path.

**Comment by florianesser** [comment]
@thorsten-reitz I was unable to reproduce the unresponsiveness problem with hale studio 3.3.2 or the latest HEAD. I get an error message almost immediately. Could you check if that still happens on your system, please?

**Comment by thorsten-reitz** [comment]
I can confirm the same behaviour - it does not become unresponsive but an error is logged in the error view:

```
java.lang.IllegalArgumentException: Illegal character in opaque part at index 28: jdbc:sqlite:/C:/Users/tr/Box Sync/staff/Data/SQLite/trento.sqlite
	at java.net.URI.create(URI.java:852)
	at eu.esdihumboldt.hale.io.jdbc.spatialite.SpatiaLiteURIBuilder.createJdbcUri(SpatiaLiteURIBuilder.java:25)
	at eu.esdihumboldt.hale.io.jdbc.spatialite.SpatiaLiteJdbcIOSupplier.<init>(SpatiaLiteJdbcIOSupplier.java:39)
	at eu.esdihumboldt.hale.io.jdbc.spatialite.reader.internal.SpatiaLiteSchemaReader.setSource(SpatiaLiteSchemaReader.java:77)
	at eu.esdihumboldt.hale.ui.io.source.AbstractProviderSource.updateConfiguration(AbstractProviderSource.java:202)
	at eu.esdihumboldt.hale.ui.io.ImportSelectSourcePage.updateConfiguration(ImportSelectSourcePage.java:472)
	at eu.esdihumboldt.hale.ui.io.ImportSelectSourcePage.updateConfiguration(ImportSelectSourcePage.java:1)
	at eu.esdihumboldt.hale.ui.io.IOWizard.validatePage(IOWizard.java:752)
	at eu.esdihumboldt.hale.ui.io.IOWizard.applyConfiguration(IOWizard.java:660)
	at eu.esdihumboldt.hale.ui.io.IOWizard.performFinish(IOWizard.java:517)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
```

**Comment by florianesser** [comment]
Support for save destinations w/ spaces can be tested w/ [this build](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/359/).

**Comment by thorsten-reitz** [comment]
LGTM.
