### ISSUE TITLE
Un-associating a codelist doesn't work

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#468]
When a code list has been associated with a property, e.g. through the assign function, it cannot be un-associated. Trying to do so results in a NPE being thrown:

```
java.lang.NullPointerException
	at eu.esdihumboldt.hale.common.codelist.config.CodeListAssociations.assignCodeList(CodeListAssociations.java:57)
	at eu.esdihumboldt.hale.ui.codelist.service.internal.CodeListServiceImpl.assignEntityCodeList(CodeListServiceImpl.java:151)
	at eu.esdihumboldt.hale.ui.common.definition.editors.DefaultPropertyEditor$4.widgetSelected(DefaultPropertyEditor.java:254)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at eu.esdihumboldt.hale.ui.function.contribution.internal.AbstractWizardAction.run(AbstractWizardAction.java:95)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:117)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:1)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.run(AbstractApplication.java:51)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.start(AbstractApplication.java:33)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by thorsten-reitz** [comment]
As a side note, that happened to a element that had an enumeration assigned before. Does it make sense at all to associate a codelist if there is already an enumeration defined?

**Comment by florianesser** [comment]
I could reproduce the problem for attributes without an enumeration restriction. I created ticket #469 for the discussion of your question.

**Comment by thorsten-reitz** [comment]
There is already a feature build for this issue, right?

**Comment by florianesser** [comment]
Yes, [this one](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/310/).

**Comment by thorsten-reitz** [comment]
LGTM.
