### ISSUE TITLE
Improve error logging on XSD parsing errors

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#485]
When the XSD parser encounters an error like an invalid `schemaLocation`, only a generic `XmlSchemaException` is logged in the error report (see below). In case the XSD parser does provide a more meaningful error message, it would be good to include it in the report.

```
java.lang.RuntimeException: org.apache.ws.commons.schema.XmlSchemaException: http://geodata.nationaalgeoregister.nl/inspire/wfs?request=DescribeFeatureType&version=2.0.0&service=WFS&outputFormat=text%2Fxml%3B%20subtype%3Dgml%2F3.2&typeName=tn-ro%3ATN.RoadTransportNetwork.RoadArea%2Ctn-ro%3ATN.RoadTransportNetwork.RoadLink%2Ctn-ro%3ATN.RoadTransportNetwork.VehicleTrafficArea
	at org.apache.ws.commons.schema.SchemaBuilder.resolveXmlSchema(SchemaBuilder.java:1898)
	at org.apache.ws.commons.schema.SchemaBuilder.handleImport(SchemaBuilder.java:1606)
	at org.apache.ws.commons.schema.SchemaBuilder.handleXmlSchemaElement(SchemaBuilder.java:224)
	at org.apache.ws.commons.schema.SchemaBuilder.build(SchemaBuilder.java:121)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:512)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:385)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:425)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:451)
	at eu.esdihumboldt.hale.io.xsd.reader.XmlSchemaReader.execute(XmlSchemaReader.java:339)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:102)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractImportProvider.execute(AbstractImportProvider.java:74)
	at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:708)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.apache.ws.commons.schema.XmlSchemaException: http://geodata.nationaalgeoregister.nl/inspire/wfs?request=DescribeFeatureType&version=2.0.0&service=WFS&outputFormat=text%2Fxml%3B%20subtype%3Dgml%2F3.2&typeName=tn-ro%3ATN.RoadTransportNetwork.RoadArea%2Ctn-ro%3ATN.RoadTransportNetwork.RoadLink%2Ctn-ro%3ATN.RoadTransportNetwork.VehicleTrafficArea
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:389)
	at org.apache.ws.commons.schema.SchemaBuilder.resolveXmlSchema(SchemaBuilder.java:1892)
	... 12 more
```

**Comment by florianesser** [comment]
TODO: Add reproduction case
