### ISSUE TITLE
inline transformation seems to be very slow and cannot be used in CLI

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#575]
Using the inline transformation slows down the transformation process significantly. When the function cell is enabled, the transformation takes ~1.5 h for 7.000 objects.
When it is disabled, the transformation takes ~7 min for 7.000 objects.

The problem occurs in a AdV BU 3D-Alignment - if testing with it is necessary I can provide it.

**Comment by JohannaOtt** [comment]
when trying to execute a transformation project containing the Inline Transformation-function via the CLI, an error occurs. As the project is supposed to be delivered to the customer via hale connect, the Inline Transformation-function should be available via CLI as well:
20.06.2018 09:20:19 ERROR e.e.c.ConceptualSchemaTransformer.transform(169) - Skipping property transformation: Executing property transformation failed. (642 times)
eu.esdihumboldt.hale.common.align.transformation.function.TransformationException: Transformation service not available for inline transformation
        at eu.esdihumboldt.cst.functions.core.inline.InlineTransformation.evaluate(InlineTransformation.java:135) ~[na:na]
        at eu.esdihumboldt.hale.common.align.transformation.function.impl.AbstractSingleTargetPropertyTransformation.evaluate(AbstractSingleTargetPropertyTransformation.java:57) ~[na:na]
        at eu.esdihumboldt.hale.common.align.transformation.function.impl.AbstractPropertyTransformation.execute(AbstractPropertyTransformation.java:102) ~[na:na]
        at eu.esdihumboldt.cst.internal.FunctionExecutor.executeTransformation(FunctionExecutor.java:224) ~[na:na]
        at eu.esdihumboldt.cst.internal.FunctionExecutor.processValid(FunctionExecutor.java:133) ~[na:na]
        at eu.esdihumboldt.hale.common.align.model.transformation.tree.visitor.CellNodeValidator.visit(CellNodeValidator.java:110) ~[na:na]
        at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.CellNodeImpl.accept(CellNodeImpl.java:103) ~[na:na]
        at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TargetNodeImpl.accept(TargetNodeImpl.java:177) ~[na:na]
        at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TargetNodeImpl.accept(TargetNodeImpl.java:173) ~[na:na]
        at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TransformationTreeImpl.accept(TransformationTreeImpl.java:129) ~[na:na]
        at eu.esdihumboldt.cst.internal.TreePropertyTransformer$2.lambda$0(TreePropertyTransformer.java:224) ~[na:na]
        at eu.esdihumboldt.hale.common.core.report.SimpleLogContext.withLog(SimpleLogContext.java:112) ~[eu.esdihumboldt.hale.common.core_3.5.0.SNAPSHOT.jar:na]
        at eu.esdihumboldt.cst.internal.TreePropertyTransformer$2.run(TreePropertyTransformer.java:181) ~[na:na]
        at eu.esdihumboldt.cst.internal.TreePropertyTransformer.publish(TreePropertyTransformer.java:264) ~[na:na]
        at eu.esdihumboldt.cst.functions.groovy.GroovyRetype.execute(GroovyRetype.java:69) ~[eu.esdihumboldt.cst.functions.groovy_3.5.0.SNAPSHOT.jar:na]
        at eu.esdihumboldt.cst.ConceptualSchemaTransformer.doTypeTransformation(ConceptualSchemaTransformer.java:327) ~[na:na]
        at eu.esdihumboldt.cst.ConceptualSchemaTransformer.transform(ConceptualSchemaTransformer.java:155) ~[na:na]
        at eu.esdihumboldt.hale.common.headless.transform.Transformation$5.run(Transformation.java:339) [eu.esdihumboldt.hale.common.headless_3.5.0.SNAPSHOT.jar:na]
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) [org.eclipse.core.jobs_3.7.0.v20150330-2103.jar:na]

**Comment by florianesser** [comment]
@stempler Since a new stateless CST is instatiated for the inline transformation of every property value, it appears that the Groovy Script that defines the corresponding type transformation is compiled over and over again, causing the long runtime. The CSTs doing the inline transformation neither share an `ExecutionContext` nor do they have access to the "outer" `ExecutionContext` and thus cannot share the compiled scripts.

**Comment by thorsten-reitz** [comment]
Can the compiled script be passed in as a parameter already?

**Comment by stempler** [comment]
@florianesser That explains it. Do you think reusing the context is feasible?

**Comment by florianesser** [comment]
Can be tested w/ [build 446](https://builds.wetransform.to/job/hale/job/hale~publish(master)/446/) or later

**Comment by thorsten-reitz** [comment]
@JohannaOtt can you please test this today?

**Comment by JohannaOtt** [comment]
Concerning the Inline Transformation being slow:
I testet with a dataset of ~1,500 objects.
With the inline transformation cell disabled, it takes about 45 seconds.
With the cell enabled it takes about 1 minute.
The transformation takes still longer but in a reasonable range from my point of view - @florianesser would you expect them to take the same amount of time?

Concerning the use of the Inline Transformation in CLI:
The error occurring on haleconnect has changed since the Inline Transformation has been updated, but it still does not work: https://wetransform.atlassian.net/browse/ING-1280. I don't know if that is related to the Inline Transformation or if that is caused by another issue on haleconnect though. @florianesser any idea about what if that could be related to the Inline Transformation? Otherwise, I can only test this issue once ING-1280 is fixed.

**Comment by florianesser** [comment]
> The transformation takes still longer but in a reasonable range from my point of view - @florianesser would you expect them to take the same amount of time?

No. If the inlined transformation contains Groovy scripts, those must be compiled once, which adds to the total execution time.

> Otherwise, I can only test this issue once ING-1280 is fixed.

I think it would be best to test this independent of hale connect by running the CLI transformation locally. That way we can be sure that it's not a hale connect issue in case there are problems.

**Comment by JohannaOtt** [comment]
Running the CLI transformation locally lead to the same error that is occuring on hale connect.
@florianesser is going to investigate what causes that error.

**Comment by JohannaOtt** [comment]
LGTM

tested with the AdV BU 3D alignment in CLI and UI - no errors are occurring any more.
