### ISSUE TITLE
Transformed Data View doesn't work

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#623]
Occasionally, I get the following stack trace when trying to open the Transformed Data View, which prevents using it:

```
org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.graphics.Image.getBounds(Image.java:1346)
	at org.eclipse.swt.widgets.Button.computeSize(Button.java:441)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:491)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:221)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:197)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1311)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1318)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1297)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1104)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4204)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:116)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:1)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.run(AbstractApplication.java:51)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.start(AbstractApplication.java:33)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

```

The issue goes away when restarting hale studio.

**Comment by florianesser** [comment]
@thorsten-reitz Did you notice anything systematic about when this happens (e.g. w/ specific projects or w/ a specific workflow) that would give us a hint how to reproduce the problem?

**Comment by florianesser** [comment]
@thorsten-reitz Did you notice anything systematic about when this happens (e.g. w/ specific projects or w/ a specific workflow) that would give us a hint how to reproduce the problem?

**Comment by thorsten-reitz** [comment]
Unfortunately I don't have a clear repro case. I wonder whether it is a timing issue, i.e. clicking something while the transformed data view transformation is still running.
Once it occurs, it is not possible to open up the transformeddata view anymore.

**Comment by JohannaOtt** [comment]
Still occurring in 4.0.0 release. Unfortunately, still no clear reproduction case.

**Comment by thorsten-reitz** [comment]
Do you mean the 4.1.0 release candidate?

**Comment by JohannaOtt** [comment]
No, I mean the 4.0.0 release.

**Comment by JohannaOtt** [comment]
@thorsten-reitz @florianesser @Kate-Lyndegaard @annat2022 Did one of you run into this lately?
If not, I would vote for closing it as there is no reproduction case.

**Comment by JohannaOtt** [comment]
Closing this now as there seems to be no clear reproduction case. A new issue can be created if it re-occurs.
