### ISSUE TITLE
HALE 3.4.0 release contains JAR with outdated classes

### ISSUE THREAD

**Issue by nmco** [halestudio/hale#630]
I was investigating the cause of the following exception that happens when exporting App-Schema mappings in HALE 3.4.0 release:
```
[08:52:26] eu.esdihumboldt.hale.io.appschema.writer.AppSchemaMappingGenerator.getGeneratedMapping()Leu/esdihumboldt/hale/io/appschema/writer/internal/AppSchemaMappingWrapper;
java.lang.NoSuchMethodError: eu.esdihumboldt.hale.io.appschema.writer.AppSchemaMappingGenerator.getGeneratedMapping()Leu/esdihumboldt/hale/io/appschema/writer/internal/AppSchemaMappingWrapper;
    at eu.esdihumboldt.hale.io.appschema.writer.AppSchemaMappingFileWriter.writeArchive(AppSchemaMappingFileWriter.java:152)
    at eu.esdihumboldt.hale.io.appschema.writer.AppSchemaMappingFileWriter.handleMapping(AppSchemaMappingFileWriter.java:87)
    at eu.esdihumboldt.hale.io.appschema.writer.AbstractAppSchemaConfigurator.execute(AbstractAppSchemaConfigurator.java:125)
    at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:107)
    at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:708)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

Long story short, I discover that JAR ``eu.esdihumboldt.hale.io.appschema_3.4.0.release.jar`` contains two version of class ``AppSchemaMappingWrapper`` one inside the ``mapping`` package another one outside. That class was moved to ``mapping`` package by this PR #519.

Looks like something strange happen with HALE 3.4.0 release, builds before and after the release don't have those outdated classes. I have tried to build HALE from 3.4.0 TAG but I step on a build issue https://github.com/halestudio/hale/issues/629.

**Comment by nmco** [comment]
Note that have tried with HALE 3.4.0 binaries downloaded from:
- https://www.wetransform.to/downloads
- https://github.com/halestudio/hale/releases/tag/3.4.0

**Comment by florianesser** [comment]
@nmco, I recreated the installer binaries and updated the release. You can redownload them from the locations you mentioned above.

**Comment by nmco** [comment]
Thank you @florianesser , downloading them right now for testing.

**Comment by nmco** [comment]
I (manually) tested both 32-bits and 64-bits Windows executables and everything seems correct:

![image](https://user-images.githubusercontent.com/1590542/41542119-1cf8905a-730c-11e8-8500-41f733d0929e.png)

So as far I'm concerned this issue can be closed, thank you @florianesser !
