### ISSUE TITLE
hsd does not load

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#707]
Version 3.5.0.SNAPSHOT
Build 444

When trying to load a hsd file created with hale studio 3.4.1 it fails with the following error. Please note that this also affects creating schemas from hsd files on haleconnect

groovy.lang.GroovyRuntimeException: Could not find matching constructor for: eu.esdihumboldt.hale.common.core.io.report.impl.IOMessageImpl(org.codehaus.groovy.runtime.GStringImpl)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1742)
	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1549)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema$_populateDefinition_closure4.doCall(XmlToSchema.groovy:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
	at org.codehaus.groovy.runtime.dgm$163.doMethodInvoke(Unknown Source)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:151)
	at eu.esdihumboldt.cst.functions.groovy.internal.AsMultiValueMetaClass.invokeMethod(AsMultiValueMetaClass.java:69)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema.populateDefinition(XmlToSchema.groovy:169)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema.parseProperty(XmlToSchema.groovy:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema$_populateGroup_closure5.doCall(XmlToSchema.groovy:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1980)
	at org.codehaus.groovy.runtime.dgm$160.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema.populateGroup(XmlToSchema.groovy:195)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema.parseType(XmlToSchema.groovy:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema$_parseSchema_closure1$_closure7.doCall(XmlToSchema.groovy:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2041)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2021)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2071)
	at org.codehaus.groovy.runtime.dgm$175.doMethodInvoke(Unknown Source)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:151)
	at eu.esdihumboldt.cst.functions.groovy.internal.AsMultiValueMetaClass.invokeMethod(AsMultiValueMetaClass.java:69)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema$_parseSchema_closure1.doCall(XmlToSchema.groovy:114)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema$_parseSchema_closure1.doCall(XmlToSchema.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.access$300(GroovyCategorySupport.java:72)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:262)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.use(DefaultGroovyMethods.java:492)
	at org.codehaus.groovy.runtime.dgm$756.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema.parseSchema(XmlToSchema.groovy:96)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.XmlToSchema.parseSchema(XmlToSchema.groovy:80)
	at eu.esdihumboldt.hale.common.schema.persist.hsd.HaleSchemaReader.execute(HaleSchemaReader.java:52)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:107)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractImportProvider.execute(AbstractImportProvider.java:74)
	at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:708)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by JohannaOtt** [comment]
It just worked with 3.5.0.SNAPSHOT
Build 25
Revision 68489bcbbb18e5daeb0416ba0742466dff4b0727
The source used for the exported schema was a csv file this time. In the case it failed, it was a FGDB - maybe that makes a difference.

**Comment by JohannaOtt** [comment]
[TN-RO.zip](https://github.com/halestudio/hale/files/2675393/TN-RO.zip)

these were the files used for the original test case

**Comment by florianesser** [comment]
Can be tested with [build 445](https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/445/) or later.

**Comment by thorsten-reitz** [comment]
@JohannaOtt can you please test this today?

**Comment by JohannaOtt** [comment]
LGTM

I tested with Build 448.
I could load the three schemas created with hs 3.4.1 (see zip above) without any issues.
I created the same schemas (hsd, hsd.gz, json) with SNAPSHOT 3.5.0 - Build 448 and was also able to reload those without any issues.
