### ISSUE TITLE
rendering target geometries cause errors when using default stlying

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#732]
hale-studio-4.0.0.SNAPSHOT-Build 457

Only some of the target geometries in the example project attached to this ticket get displayed on specific zoom levels in the Map View and the loading ("clock") sign won't disappear.
[Geologie_GK_25 (Geologische Karte 1 25000).zip](https://github.com/halestudio/hale/files/2868116/Geologie_GK_25.Geologische.Karte.1.25000.zip)

While loading the map, errors occur in the error log - example stack trace:
`java.lang.NullPointerException
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.StyledInstanceMarker.initStyle(StyledInstanceMarker.java:121)
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.StyledInstanceMarker.applyFill(StyledInstanceMarker.java:383)
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.StyledInstanceMarker.applyFill(StyledInstanceMarker.java:1)
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.InstanceMarker.paintPolygon(InstanceMarker.java:415)
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.InstanceMarker.paintGeometry(InstanceMarker.java:289)
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.InstanceMarker.paintGeometry(InstanceMarker.java:195)
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.InstanceMarker.doPaintMarker(InstanceMarker.java:146)
	at eu.esdihumboldt.hale.ui.views.styledmap.painter.InstanceMarker.doPaintMarker(InstanceMarker.java:1)
	at de.fhg.igd.mapviewer.marker.BoundingBoxMarker.paintMarker(BoundingBoxMarker.java:74)
	at de.fhg.igd.mapviewer.marker.BoundingBoxMarker.paintMarker(BoundingBoxMarker.java:1)
	at de.fhg.igd.mapviewer.marker.AbstractMarker.paint(AbstractMarker.java:45)
	at de.fhg.igd.mapviewer.waypoints.MarkerWaypointRenderer.paintWaypoint(MarkerWaypointRenderer.java:42)
	at de.fhg.igd.mapviewer.waypoints.MarkerWaypointRenderer.paintWaypoint(MarkerWaypointRenderer.java:1)
	at de.fhg.igd.mapviewer.waypoints.CustomWaypointPainter.processWaypoint(CustomWaypointPainter.java:297)
	at de.fhg.igd.mapviewer.waypoints.CustomWaypointPainter.repaintTile(CustomWaypointPainter.java:231)
	at de.fhg.igd.mapviewer.AbstractTileOverlayPainter$TilePaintDelegate.paintTile(AbstractTileOverlayPainter.java:98)
	at de.fhg.igd.mapviewer.AbstractTileOverlayPainter$1.run(AbstractTileOverlayPainter.java:637)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

This only happens when using the default styling. As soon as the styling is set to a specific color, they display quick and fine.

It might be important to take into account that the geometry mapping is realised on a higher level (attribut "shape" above AbstractGeometry) - that is the only thing coming to my mind that is a bit extraordinary with this alignment.

**Comment by florianesser** [comment]
[Build with fix](http://build-artifacts.wetransform.to.s3-eu-central-1.amazonaws.com/index.html?prefix=travisci/hale/77/)

**Comment by florianesser** [comment]
Looks good now with the example project provided, closing.
