### ISSUE TITLE
LinkageError: loader constraint violation error on javax.xml.namespace.QName class

### ISSUE THREAD

**Issue by fernandor777** [halestudio/hale#740]
Working on new feature for App-schema plugin I faced a LinkageError on QName class.

Checking HALE available libraries on its folders I found two javax.xml.namespace.QName class:
```
hale-studio-3.5.0-win32.win32.x86_64\jre\lib\rt.jar -> javax\xml\namespace\QName.class

hale-studio-3.5.0-win32.win32.x86_64\plugins\xml-apis_1.4.1.i20180427.jar -> javax\xml\namespace\QName.class
```

Manually removing xml-apis_1.4.1.i20180427.jar file and restarting HALE solved the problem, and App-schema plugin exported its mappings whitout problems.

So maybe this xml-apis_1.4.1.i20180427.jar  dependency have classes already included on JDK since 1.5 version and collides with them.  Searching about this jar seems like it is a very old Apache XML commons xml apis which was merged on Java 5:
https://docs.oracle.com/javase/7/docs/api/javax/xml/namespace/QName.html

This kind of LinkageError seems to be common on OSGI enviromnets, a possible solution can be remove (switch to provided/ exclude) xml-apis dependency so entire application can use JDK's xml apis.

See also:
https://chamibuddhika.wordpress.com/2012/05/15/learn-by-errors-java-osgi/

Here the error stracktrace:
```
java.lang.LinkageError: loader constraint violation: when resolving method "javax.xml.bind.JAXBElement.<init>(Ljavax/xml/namespace/QName;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Object;)V" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, it/geosolutions/hale/io/appschema/impl/internal/generated/app_schema/ObjectFactory, and the class loader (instance of <bootloader>) for the method's defining class, javax/xml/bind/JAXBElement, have different Class objects for the type javax/xml/namespace/QName used in the signature
	at it.geosolutions.hale.io.appschema.impl.internal.generated.app_schema.ObjectFactory.createAppSchemaDataAccess(ObjectFactory.java:185)
	at it.geosolutions.hale.io.appschema.writer.AppSchemaMappingGenerator.writeMapping(AppSchemaMappingGenerator.java:724)
	at it.geosolutions.hale.io.appschema.writer.AppSchemaMappingGenerator.writeMappingConf(AppSchemaMappingGenerator.java:678)
	at it.geosolutions.hale.io.appschema.writer.AppSchemaMappingFileWriter.writeMappingFile(AppSchemaMappingFileWriter.java:97)
	at it.geosolutions.hale.io.appschema.writer.AppSchemaMappingFileWriter.handleMapping(AppSchemaMappingFileWriter.java:84)
	at it.geosolutions.hale.io.appschema.writer.AbstractAppSchemaConfigurator.execute(AbstractAppSchemaConfigurator.java:125)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:107)
	at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:708)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by stempler** [comment]
If it's completely incorporated into the JDK it can be excluded like this is already done [here](https://github.com/halestudio/hale-platform/blob/8fc1490246b88b0aacb81d073287b97911d27eb6/build.gradle#L163). Seems strange though that this did not clash before. Any idea on what might have changed?

**Comment by fernandor777** [comment]
Probably a classpath loaders issue due to Eclipse OSGI loaded module (app-schema) using JDK QName class versus HALE core using the other QName class from xml-apis.jar

**Comment by thorsten-reitz** [comment]
@fernandor777 can this issue be closed?

**Comment by fernandor777** [comment]
@thorsten-reitz yes, it can be closed.
