### ISSUE TITLE
"Unknown owner type" error when opening projects from hale connect

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#752]
Version 4.0.0.SNAPSHOT
Build 557890456

I want to open a transformation project from hale connect using the wetransform-support account. When doing so, this pop up window with erroe messages appear as soon as I hit the "Select" button:
![grafik](https://user-images.githubusercontent.com/34163838/63077568-ffab4900-bf38-11e9-9c2b-7de137a9d780.png)
These are the error messages related to it 
![grafik](https://user-images.githubusercontent.com/34163838/63077692-76484680-bf39-11e9-9253-c54f22def2c4.png)
This is the stacktrace of one of them:
java.lang.IllegalStateException: Unknown owner type
	at eu.esdihumboldt.hale.io.haleconnect.HaleConnectProjectInfo.getOwner(HaleConnectProjectInfo.groovy:105)
	at eu.esdihumboldt.hale.io.haleconnect.ui.projects.ChooseHaleConnectProjectWizardPage$6.getText(ChooseHaleConnectProjectWizardPage.groovy:328)
	at org.eclipse.jface.viewers.ColumnLabelProvider.update(ColumnLabelProvider.java:34)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
	at org.eclipse.jface.viewers.AbstractTableViewer.doUpdateItem(AbstractTableViewer.java:391)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:475)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2158)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefreshAll(AbstractTableViewer.java:674)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:612)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:604)
	at org.eclipse.jface.viewers.AbstractTableViewer.lambda$0(AbstractTableViewer.java:566)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1446)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1407)
	at org.eclipse.jface.viewers.AbstractTableViewer.inputChanged(AbstractTableViewer.java:566)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:286)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1684)
	at eu.esdihumboldt.hale.io.haleconnect.ui.projects.ChooseHaleConnectProjectWizardPage$GetProjectsCallback$1.run(ChooseHaleConnectProjectWizardPage.groovy:103)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3537)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at eu.esdihumboldt.hale.io.haleconnect.ui.projects.ChooseHaleConnectProjectWizard.openSelectProject(ChooseHaleConnectProjectWizard.java:70)
	at eu.esdihumboldt.hale.io.haleconnect.ui.projects.HaleConnectSource.selectProject(HaleConnectSource.java:273)
	at eu.esdihumboldt.hale.io.haleconnect.ui.projects.HaleConnectSource.access$2(HaleConnectSource.java:272)
	at eu.esdihumboldt.hale.io.haleconnect.ui.projects.HaleConnectSource$5.widgetSelected(HaleConnectSource.java:206)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at eu.esdihumboldt.hale.ui.service.project.internal.ProjectServiceImpl$8.run(ProjectServiceImpl.java:880)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4567)
	at eu.esdihumboldt.hale.ui.service.project.internal.ProjectServiceImpl.open(ProjectServiceImpl.java:871)
	at eu.esdihumboldt.hale.ui.service.project.handler.OpenProjectHandler.execute(OpenProjectHandler.java:40)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:161)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:116)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:1)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.run(AbstractApplication.java:51)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.start(AbstractApplication.java:33)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)

**Comment by Kate-Lyndegaard** [comment]
I also receive this error quite often, and the first few times I hit it, it was quite disturbing.

Workflow:

1. Log-in to hale studio with wetransform support credentials
2. Open a transformation project which already exists on haleconnect in hale studio
3. Go to File --> Share a project on haleconnect
4. In the Load project dialog, the error that Johanna originally reported appears if the project already exists on haleconnect. 

I think that this bug is particulary relevant, because users will encounter problems when editing transformation projects in hale studio and trying to upload updated projects to haleconnect.

**Comment by florianesser** [comment]
> In some cases, there is a red message that states: "The current project to be exported was not originally imported from hale connect", however that is not true. The vast majority of transformation projects I've created on haleconnect were originally 'shared' (not exported) from hale studio.

@Kate-Lyndegaard This message is shown if a project was not opened directly from hale connect via the import wizard but e.g. downloaded manually as a `.halez` and then opened locally.

**Comment by florianesser** [comment]
@JohannaOtt @Kate-Lyndegaard The issue should be fixed and can be tested with [this build](http://build-artifacts.wetransform.to.s3-eu-central-1.amazonaws.com/index.html?prefix=travisci/hale/38/).

**Comment by Kate-Lyndegaard** [comment]
@florianesser Wow, I just tested this issue and the problem is fixed. That is a big improvement in my opinion. Great, thank you!

**Comment by JohannaOtt** [comment]
The error is gone, but organisations are not recognised anymore when exporting transformation projects: 
![grafik](https://user-images.githubusercontent.com/34163838/69251124-3684a100-0bb1-11ea-9f46-fc3ef9b19279.png)

**Comment by florianesser** [comment]
@JohannaOtt Nice catch, thanks! [Here's a new version](http://build-artifacts.wetransform.to.s3-eu-central-1.amazonaws.com/index.html?prefix=travisci/hale/40/) where that should be fixed.

**Comment by JohannaOtt** [comment]
![grafik](https://user-images.githubusercontent.com/34163838/69344827-58912880-0c70-11ea-95ec-d1300306af59.png)
LGTM

**Comment by JohannaOtt** [comment]
I am sorry, I obviously did not check good enough. If you export a project to hale connect and click on 'update an eyisting project', there are still some wrong values in the owner column: 
![grafik](https://user-images.githubusercontent.com/34163838/69438105-c73fb600-0d44-11ea-97da-3af2aa48601c.png)

**Comment by florianesser** [comment]
@JohannaOtt [Here's an updated version](http://build-artifacts.wetransform.to.s3-eu-central-1.amazonaws.com/index.html?prefix=travisci/hale/42/) where this should be fixed.

**Comment by JohannaOtt** [comment]
![grafik](https://user-images.githubusercontent.com/34163838/69543303-91d9d900-0f8d-11ea-984b-dbed2bed9310.png)
Some owners still are not recognised, but these users also don't exist anymore in the system. So maybe that is the expected behavior for those.

**Comment by florianesser** [comment]
> So maybe that is the expected behavior for those.

Yes, that is expected.

**Comment by JohannaOtt** [comment]
Ok, then I would consider this ticket as done.
