### ISSUE TITLE
Update packaged JRE to add support for TLS v1.2

### ISSUE THREAD

**Issue by florianesser** [halestudio/hale#758]
Login to a (non-default) hale connect deployment fails the following error show below. The site uses TLS v1.2 (`openssl s_client` output below).

```
eu.esdihumboldt.hale.io.haleconnect.HaleConnectException: Received fatal alert: protocol_version
	at eu.esdihumboldt.hale.io.haleconnect.internal.HaleConnectServiceImpl.login(HaleConnectServiceImpl.groovy:349)
	at eu.esdihumboldt.hale.io.haleconnect.ui.HaleConnectLoginHandler$1.run(HaleConnectLoginHandler.java:92)
	at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor$1.run(ThreadProgressMonitor.java:122)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at com.haleconnect.api.user.v1.ApiClient.execute(ApiClient.java:969)
	at com.haleconnect.api.user.v1.api.LoginApi.loginWithHttpInfo(LoginApi.java:141)
	at com.haleconnect.api.user.v1.api.LoginApi.login(LoginApi.java:127)
	at eu.esdihumboldt.hale.io.haleconnect.internal.HaleConnectServiceImpl.login(HaleConnectServiceImpl.groovy:328)
	... 3 more
	Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
		at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
		... 25 more
```

```
New, TLSv1.2, Cipher is DHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES256-GCM-SHA384
    Session-ID: 9DEB3C67DEB99C1B6D61BBBAEC47B079D3300D348F446878E7D23C7B4AF42E1F
    Session-ID-ctx:
    Master-Key: 18D805FC683DA4E042259B9D4FB319AAFA98C475A65BA2C9F6E28F339A350A72FD5634EF52351E0F0408F8D23D27C201
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1568646608
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by stempler** [comment]
I tested this about a week ago - using a current Java 8 update (instead of the version shipped with hale studio) it works w/o any additional changes.

**Comment by florianesser** [comment]
Thanks @stempler, I'll test that.

**Comment by florianesser** [comment]
@stempler Using a more recent Java 8 update solved this, so I would suggest that we update the packaged JRE in the next release.

**Comment by JohannaOtt** [comment]
This issue also keeps services from the ITEOS platform from being loaded to hale studio with this error message: 
![grafik](https://user-images.githubusercontent.com/34163838/68196146-6f6d2500-ffb8-11e9-9966-f0cbc3e0e034.png)
It can be loaded if a newer Java version is used (I tried with 1.8.0_191).

**Comment by florianesser** [comment]
@JohannaOtt Could you challenge this?

**Comment by JohannaOtt** [comment]
> 
> 
> I had a similar issue trying to load a WFS service in hale studio - using a current Java 8 update (instead of the version shipped with hale studio) worked in that case w/o any additional changes.

@stempler do you still know what kind of WFS was affected by that so I can test it for challenging?

**Comment by JohannaOtt** [comment]
I challenged the following:
* Logging in from hale connect to the alternative hale connect system that caused the issue -> works
* Loading the service I reported yesterday -> works

Therefore I consider this ticket being Done.
