### ISSUE TITLE
Cannot load HabitatsAndBiotopesDistribution INSPIRE schema in halestudio

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [halestudio/hale#761]
I am currently working on [WGS-414](https://wetransform.atlassian.net/browse/WGS-414?focusedCommentId=24365&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&utm_medium=referral-external&utm_source=jira-slack&utm_term=#comment-24365). 
I need to map the source data to the INSPIRE HabitatsAndBiotopesDistribution schema, however this schema only exists in the EU draft schemas here: http://inspire.ec.europa.eu/draft-schemas/hbd/3.0/
Unfortunately, this schema will not load in hale studio: http://inspire.ec.europa.eu/draft-schemas/hbd/3.0/HabitatsAndBiotopesDistribution.xsd
I receive a: "Failed Please see the report details" error message. The reports states:
`java.lang.RuntimeException: org.apache.ws.commons.schema.XmlSchemaException: http://inspire.ec.europa.eu/schemas/base/3.3BaseTypes.xsd
	at org.apache.ws.commons.schema.SchemaBuilder.resolveXmlSchema(SchemaBuilder.java:1898)
	at org.apache.ws.commons.schema.SchemaBuilder.handleImport(SchemaBuilder.java:1606)
	at org.apache.ws.commons.schema.SchemaBuilder.handleXmlSchemaElement(SchemaBuilder.java:224)
	at org.apache.ws.commons.schema.SchemaBuilder.build(SchemaBuilder.java:121)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:512)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:385)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:425)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:451)
	at eu.esdihumboldt.hale.io.xsd.reader.XmlSchemaReader.execute(XmlSchemaReader.java:339)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:107)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractImportProvider.execute(AbstractImportProvider.java:74)
	at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:708)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.apache.ws.commons.schema.XmlSchemaException: http://inspire.ec.europa.eu/schemas/base/3.3BaseTypes.xsd
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:389)
	at org.apache.ws.commons.schema.SchemaBuilder.resolveXmlSchema(SchemaBuilder.java:1892)
	... 12 more
`
As a workaround, I loaded the rc3 hbd schema (http://inspire.ec.europa.eu/draft-schemas/hbd/3.0rc3/HabitatsAndBiotopesDistribution.xsd) to complete the transformation, as it loads without error in halestudio.
It would be better, to load the most current schema available.

**Comment by stempler** [comment]
The schema has a wrong reference to an imported schema, so the error is with the schema:

```
<import namespace="http://inspire.ec.europa.eu/schemas/base/3.3" schemaLocation="http://inspire.ec.europa.eu/schemas/base/3.3BaseTypes.xsd"/>
```

I guess because this schema did not make to the official schemas and no 4.0 release was created this did not occur to anyone.

**Comment by Kate-Lyndegaard** [comment]
OK, I will use the rc3 hbd schema (http://inspire.ec.europa.eu/draft-schemas/hbd/3.0rc3/HabitatsAndBiotopesDistribution.xsd). 
EU member states are required to report habitat distribution datasets to the EEA every six years, so all member states have this data. Strange that the schema has not been released.
