### ISSUE TITLE
Support conversion of BigInteger when writing to GeoPackage

### ISSUE THREAD

**Issue by thorsten-reitz** [halestudio/hale#788]
Currently, writing to GeoPackage does not work if the binding of data in hale studio is BigInteger:

```
mil.nga.geopackage.GeoPackageException: Unsupported Number type: BigInteger
	at mil.nga.geopackage.user.UserRow.columnToContentValue(UserRow.java:121)
	at mil.nga.geopackage.user.UserRow.toContentValues(UserRow.java:73)
	at mil.nga.geopackage.user.UserDao.insert(UserDao.java:160)
	at eu.esdihumboldt.hale.io.geopackage.GeopackageInstanceWriter.writeInstances(GeopackageInstanceWriter.java:223)
	at eu.esdihumboldt.hale.io.geopackage.GeopackageInstanceWriter.execute(GeopackageInstanceWriter.java:156)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:107)
	at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:708)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by thorsten-reitz** [comment]
Temporary workaround: Use a target schema (e.g. HSD) where the binding of the fields in question has been manually changed to `java.lang.Integer` or `java.lang.Long`.

**Comment by thorsten-reitz** [comment]
Estimated Effort: 4h

**Comment by thorsten-reitz** [comment]
Tested, LGTM.
