### ISSUE TITLE
Implement potential date value fix when reading geopackages

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#887]
According to the [spec](http://www.geopackage.org/spec/#r5), the data type DATETIME calls for ISO-8601 encoded values in the UTC time zone: "DATETIME ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator character and Z suffix for coordinated universal time (UTC) encoded in either UTF-8 or UTF-16."
If this encoding is not fulfilled, importing such geopackage data results in a lot of error messages in the logs. The data is still imported and used in the transformation
As there are cases, where the "Z" is missing, a functionality should be added to the Geopackage reader that adds an additional "Z" to the values and re-tries importing the values to the database.
In case that is successful, a warning should be provided in the report list to inform the user that the source data is missing a "Z". It might make sense to reduce the number of warnings displayed in the console and add an information on how often it occurred (if that is feasible), so users to not get a warning for every single object.
In case that is not successful, the behavior should be the same as it currently is.
This will help avoid many error messages filling the console.

This is the error message displayed
`17.03.2021 15:03:33 WARN  e.e.h.c.i.g.InstanceBuilder.processValue(451) - Failed to auto-convert property or instance value
org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type java.time.Instant for value '2015-08-30T18:13:24'; nested exception is java.time.format.DateTimeParseException: Text '2015-08-30T18:13:24' could not be parsed at index 19
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[na:na]
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:171) ~[na:na]
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:154) ~[na:na]
        at eu.esdihumboldt.hale.common.convert.ConversionUtil.getAs(ConversionUtil.java:58) ~[eu.esdihumboldt.hale.common.convert_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.processValue(InstanceBuilder.groovy:449) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createPropertyValue(InstanceBuilder.groovy:404) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.access$0(InstanceBuilder.groovy) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder$_addProperty_closure1.doCall(InstanceBuilder.groovy:272) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.Closure.call(Closure.java:418) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2041) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2021) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2071) [groovy_2.4.14.i20180424.jar:2.4.14]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.addProperty(InstanceBuilder.groovy:252) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.internalCreateNode(InstanceBuilder.groovy:210) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.util.groovy.builder.BuilderBase.methodMissing(BuilderBase.groovy:91) [eu.esdihumboldt.util.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.util.groovy.builder.BuilderBase.createNode(BuilderBase.groovy:112) [eu.esdihumboldt.util.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createProperty(InstanceBuilder.groovy:188) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createProperty(InstanceBuilder.groovy) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.io.geopackage.internal.TableInstanceBuilder$_createInstance_closure1$_closure2.doCall(TableInstanceBuilder.groovy:110) [eu.esdihumboldt.hale.io.geopackage_4.0.0.release.jar:na]
        at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.Closure.call(Closure.java:418) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.Closure.call(Closure.java:434) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2139) [groovy_2.4.14.i20180424.jar:2.4.14]
        at eu.esdihumboldt.hale.io.geopackage.internal.TableInstanceBuilder$_createInstance_closure1.doCall(TableInstanceBuilder.groovy:75) [eu.esdihumboldt.hale.io.geopackage_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.io.geopackage.internal.TableInstanceBuilder$_createInstance_closure1.doCall(TableInstanceBuilder.groovy) [eu.esdihumboldt.hale.io.geopackage_4.0.0.release.jar:na]
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264) [groovy_2.4.14.i20180424.jar:2.4.14]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) [groovy_2.4.14.i20180424.jar:2.4.14]
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236) [groovy_2.4.14.i20180424.jar:2.4.14]
        at eu.esdihumboldt.util.groovy.builder.BuilderBase.methodMissing(BuilderBase.groovy:94) [eu.esdihumboldt.util.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.util.groovy.builder.BuilderBase.createNode(BuilderBase.groovy:112) [eu.esdihumboldt.util.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createInstance(InstanceBuilder.groovy:156) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createInstance(InstanceBuilder.groovy:132) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createInstance(InstanceBuilder.groovy) [eu.esdihumboldt.hale.common.instance.groovy_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.io.geopackage.internal.TableInstanceBuilder.createInstance(TableInstanceBuilder.groovy:72) [eu.esdihumboldt.hale.io.geopackage_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.io.geopackage.internal.GeopackageFeatureCollection$FeaturesIterator.next(GeopackageFeatureCollection.java:152) [eu.esdihumboldt.hale.io.geopackage_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.io.geopackage.internal.GeopackageFeatureCollection$FeaturesIterator.next(GeopackageFeatureCollection.java:1) [eu.esdihumboldt.hale.io.geopackage_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.model.impl.MultiInstanceCollection$MultiInstanceCollectionResourceIterator.next(MultiInstanceCollection.java:192) [eu.esdihumboldt.hale.common.instance_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.model.impl.MultiInstanceCollection$MultiInstanceCollectionResourceIterator.next(MultiInstanceCollection.java:1) [eu.esdihumboldt.hale.common.instance_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.orient.storage.StoreInstancesJob.lambda$0(StoreInstancesJob.java:219) [eu.esdihumboldt.hale.common.instance.orient_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.core.report.SimpleLogContext.withLog(SimpleLogContext.java:112) ~[eu.esdihumboldt.hale.common.core_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.common.instance.orient.storage.StoreInstancesJob.run(StoreInstancesJob.java:204) [eu.esdihumboldt.hale.common.instance.orient_4.0.0.release.jar:na]
        at eu.esdihumboldt.hale.ui.service.instance.internal.orient.OrientInstanceService$3.run(OrientInstanceService.java:312) ~[na:na]
        at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor.runWithProgressDialog(ThreadProgressMonitor.java:156) ~[na:na]
        at eu.esdihumboldt.hale.ui.service.instance.internal.orient.OrientInstanceService.addSourceInstances(OrientInstanceService.java:307) ~[na:na]
        at eu.esdihumboldt.hale.ui.io.instance.InstanceImportAdvisor.handleResults(InstanceImportAdvisor.java:104) ~[na:na]
        at eu.esdihumboldt.hale.ui.io.instance.InstanceImportAdvisor.handleResults(InstanceImportAdvisor.java:1) ~[na:na]
        at eu.esdihumboldt.hale.ui.service.project.ProjectResourcesUtil$2.run(ProjectResourcesUtil.java:215) ~[na:na]
        at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor$1.run(ThreadProgressMonitor.java:122) ~[na:na]
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122) ~[na:na]
Caused by: java.time.format.DateTimeParseException: Text '2015-08-30T18:13:24' could not be parsed at index 19
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[na:1.8.0_232]
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_232]
        at java.time.Instant.parse(Instant.java:395) ~[na:1.8.0_232]
        at eu.esdihumboldt.hale.common.convert.core.StringToInstantConverter.convert(StringToInstantConverter.java:34) ~[na:na]
        at eu.esdihumboldt.hale.common.convert.core.StringToInstantConverter.convert(StringToInstantConverter.java:1) ~[na:na]
        at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:517) ~[na:na]
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:35) ~[na:na]
        ... 68 common frames omitted`

**Comment by thorsten-reitz** [comment]
LGTM. Tested with build https://builds.wetransform.to/job/hale/job/hale%7Epublish(master)/546/
