### ISSUE TITLE
ERROR writing deegree SQL mapping (with preset INSPIRE schemas/elu/4.0)

### ISSUE THREAD

**Issue by axza** [halestudio/hale#893]
Exporting the deegree SQL mapping while using the Target scheme `INSPIRE Existing Land Use 4.0` [schemas/elu/4.0](http://inspire.ec.europa.eu/schemas/elu/4.0) from preset is followed by this error.

ERROR:
```
class org.deegree.commons.xml.XMLProcessingException: Severe error in schema document (systemId: null, line: -1, column: -1) Premature end of file.
<< is empty >>
	at org.deegree.commons.xml.schema.XMLSchemaInfoSet.loadModel(XMLSchemaInfoSet.java:489)
	at org.deegree.commons.xml.schema.XMLSchemaInfoSet.<init>(XMLSchemaInfoSet.java:137)
	at org.deegree.gml.schema.GMLSchemaInfoSet.<init>(GMLSchemaInfoSet.java:206)
	at org.deegree.gml.schema.GMLAppSchemaReader.<init>(GMLAppSchemaReader.java:138)
	at eu.esdihumboldt.hale.io.deegree.mapping.MappingHelper.readApplicationSchema(MappingHelper.groovy:56)
	at eu.esdihumboldt.hale.io.deegree.mapping.MappingWriter.getMappedSchema(MappingWriter.java:294)
	at eu.esdihumboldt.hale.io.deegree.mapping.MappingWriter.saveConfig(MappingWriter.java:134)
	at eu.esdihumboldt.hale.io.deegree.mapping.MappingAlignmentWriter.writeResult(MappingAlignmentWriter.java:116)
	at eu.esdihumboldt.hale.io.deegree.mapping.MappingAlignmentWriter.execute(MappingAlignmentWriter.java:78)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:107)
	at eu.esdihumboldt.hale.ui.io.IOWizard$3.run(IOWizard.java:708)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Export using the same scheme as a local saved file works as expected.

**Comment by florianesser** [comment]
Hi @axza,

Thanks for reaching out! The error message looks like the problem is related to the recently added automatic redirect of INSPIRE schema URLs from http to https. Could you please try to manually change the INSPIRE schema URLs in your `halex` file from http to https? You can do that by finding the `resource` elements that have the value `eu.esdihumboldt.hale.io.xsd.reader` in its `provider-id` attribute and changing the value of the `<setting name="source">` element (see example below).

```
    <resource action-id="eu.esdihumboldt.hale.io.schema.read.target" provider-id="eu.esdihumboldt.hale.io.xsd.reader">
        <setting name="charset">UTF-8</setting>
        <setting name="onlyElementsMappable">true</setting>
        <setting name="resourceId">0d882019-5f05-42ab-8a47-520438094bd2</setting>
        <setting name="source">https://inspire.ec.europa.eu/schemas/ef/4.0/EnvironmentalMonitoringFacilities.xsd</setting>
        <setting name="contentType">eu.esdihumboldt.hale.io.xsd</setting>
    </resource>
```

Let me know if that changes anything or if you have any questions.

All the best,

Florian

**Comment by axza** [comment]
Ahoi @florianesser!
Thanks for the explanation and directions.

changed
 `<setting name="source">resource1/ExistingLandUse.xsd</setting>`
to
`<setting name="source">https://inspire.ec.europa.eu/https-schemas/elu/4.0/ExistingLandUse.xsd</setting>`
and now the alignment-export works as expected.
