### ISSUE TITLE
NullPointerException using InstanceAccessor

### ISSUE THREAD

**Issue by stempler** [halestudio/hale#93]
No simple case for reproduction found yet. In this example happened with a property nested at least three levels deep, with a choice in between.

```
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:40)
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:89)
	at eu.esdihumboldt.util.groovy.paths.PathImpl.<init>(PathImpl.java:48)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceAccessor$1.apply(InstanceAccessor.groovy:64)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceAccessor$1.apply(InstanceAccessor.groovy)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:582)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectMany(DefaultGroovyMethods.java:2520)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectMany(DefaultGroovyMethods.java:2496)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceAccessor.findChildPaths(InstanceAccessor.groovy:108)
	at eu.esdihumboldt.util.groovy.paths.AbstractAccessor.findChildren(AbstractAccessor.java:102)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceAccessor.findChildren(InstanceAccessor.groovy:77)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceAccessor.findChildren(InstanceAccessor.groovy)
	at eu.esdihumboldt.util.groovy.paths.AbstractAccessor.getProperty(AbstractAccessor.java:70)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
	at Script1.sourceNameFromModellart(Script1.groovy:3)
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:368)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
	at Script1$_run_closure1.doCall(Script1.groovy:17)
	at Script1$_run_closure1.doCall(Script1.groovy)
	at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:75)
	at eu.esdihumboldt.util.groovy.builder.BuilderBase.methodMissing(BuilderBase.groovy:94)
	at eu.esdihumboldt.util.groovy.builder.BuilderBase.createNode(BuilderBase.groovy:112)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createInstance(InstanceBuilder.groovy:156)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createInstance(InstanceBuilder.groovy:132)
	at eu.esdihumboldt.hale.common.instance.groovy.InstanceBuilder.createInstance(InstanceBuilder.groovy)
	at eu.esdihumboldt.cst.functions.groovy.internal.TargetCollector.toMultiValue(TargetCollector.java:115)
	at eu.esdihumboldt.cst.functions.groovy.GroovyTransformation$1.process(GroovyTransformation.java:137)
	at eu.esdihumboldt.util.groovy.sandbox.DefaultGroovyService.evaluate(DefaultGroovyService.java:163)
	at eu.esdihumboldt.cst.functions.groovy.GroovyTransformation.evaluate(GroovyTransformation.java:120)
	at eu.esdihumboldt.hale.common.align.custom.groovy.CustomGroovyTransformation.evaluate(CustomGroovyTransformation.java:103)
	... 13 more
```

**Comment by stempler** [comment]
Not been able to reproduce that again. Maybe a side effect of #96 (at least in that case).
Proper handling of the issue requires an example though, so we can determine where and how this should be handled.

**Comment by stempler** [comment]
No reproduction case.
