### ISSUE TITLE
Classification is running into an error for complex source elements with values on top level

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#947]
When the source element for a classification function is a complex element which has a value, the classification fails with the following error message:
`org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type eu.esdihumboldt.hale.common.instance.orient.storage.DatabaseHandle$InstanceHandle to type java.lang.String
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:475)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:154)
	at eu.esdihumboldt.hale.common.align.transformation.function.impl.PropertyValueImpl.getValueAs(PropertyValueImpl.java:77)
	at eu.esdihumboldt.cst.functions.core.ClassificationMapping.evaluate(ClassificationMapping.java:51)
	at eu.esdihumboldt.hale.common.align.transformation.function.impl.AbstractSingleTargetPropertyTransformation.evaluate(AbstractSingleTargetPropertyTransformation.java:57)
	at eu.esdihumboldt.hale.common.align.transformation.function.impl.AbstractPropertyTransformation.execute(AbstractPropertyTransformation.java:102)
	at eu.esdihumboldt.cst.internal.FunctionExecutor.executeTransformation(FunctionExecutor.java:224)
	at eu.esdihumboldt.cst.internal.FunctionExecutor.processValid(FunctionExecutor.java:133)
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.visitor.CellNodeValidator.visit(CellNodeValidator.java:110)
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.CellNodeImpl.accept(CellNodeImpl.java:103)
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TargetNodeImpl.accept(TargetNodeImpl.java:177)
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TargetNodeImpl.accept(TargetNodeImpl.java:173)
	at eu.esdihumboldt.hale.common.align.model.transformation.tree.impl.TransformationTreeImpl.accept(TransformationTreeImpl.java:129)
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer$2.lambda$0(TreePropertyTransformer.java:224)
	at eu.esdihumboldt.hale.common.core.report.SimpleLogContext.withLog(SimpleLogContext.java:112)
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer$2.run(TreePropertyTransformer.java:181)
	at eu.esdihumboldt.cst.internal.TreePropertyTransformer.publish(TreePropertyTransformer.java:264)
	at eu.esdihumboldt.cst.functions.core.Retype.execute(Retype.java:71)
	at eu.esdihumboldt.cst.ConceptualSchemaTransformer.doTypeTransformation(ConceptualSchemaTransformer.java:327)
	at eu.esdihumboldt.cst.ConceptualSchemaTransformer.transform(ConceptualSchemaTransformer.java:155)
	at eu.esdihumboldt.hale.ui.service.instance.internal.orient.OrientInstanceService$5.run(OrientInstanceService.java:473)
	at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor$1.run(ThreadProgressMonitor.java:122)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
`

There is a halez file attached with a minimal example dataset for which this error occurs.
[ClassificationTypeIssue.zip](https://github.com/halestudio/hale/files/7635843/ClassificationTypeIssue.zip)

The element for which the error occurs ([SO_Plan.planArt](https://repository.gdi-de.org/schemas/de.xleitstelle.xplanung/5.0/XPlanGML_SonstigePlanwerke.xsd) uses the type [gml:CodeType](http://schemas.opengis.net/iso/19139/20060504/gml/basicTypes.xsd).

**Comment by florianesser** [comment]
Same underlying issue as in #1025, is not reproducible any longer with latest `master` build.

**Comment by stempler** [comment]
Fixed in 5.2.0
